# Generated by Django 5.1.2 on 2024-11-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0003_alter_archivos_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rotation_period', models.IntegerField()),
                ('orbital_period', models.IntegerField()),
                ('climate', models.CharField(max_length=100)),
                ('terrain', models.CharField(max_length=100)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Planeta',
                'verbose_name_plural': 'Planetas',
                'ordering': ['-name'],
            },
        ),
    ]
